{% set version = "1.4.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-upsetr
  version: {{ version|replace("-", "_") }}

source:
  fn: UpSetR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/UpSetR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/UpSetR/UpSetR_{{ version }}.tar.gz
  sha256: 351e5fee64204cf77fd378cf2a2c0456cc19d4d98a2fd5f3dac74b69a505f100

build:
  noarch: generic
  number: 4

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-plyr
    - r-scales

  run:
    - r-base
    - r-ggplot2
    - r-gridextra
    - r-plyr
    - r-scales

test:
  commands:
    - $R -e "library('UpSetR')"  # [not win]
    - "\"%R%\" -e \"library('UpSetR')\""  # [win]

about:
  home: http://github.com/hms-dbmi/UpSetR
  license: MIT
  summary: Creates visualizations of intersecting sets using a novel matrix design, along with visualizations of several common set, element and attribute related tasks.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - dlaehnemann
