appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: nglNbPCoBFMIOrGHsmA9jzYjmmPm4GRyJ+mrQ824SX4AiJi4ssQhjrIEg0lmiJOOJ6edcLq6FNLAC2bmc3h7WQ+jnWjC5Kwl0EP5/hwqM0bj2IMjG/MSOFkQOgAwW871Qsm1SjjMCNibY8uN2Hqn2NFV3ijoUyoGz3LcBdb7VyBIvdUuq+zCYzGxVVcVElx8Fs+aD4qgaIc8+pLMiX8/sGwhu6T11zpLgiOC69Yc+KCJfGmScdurF8v9CjRSYUNpxBCWnnP/tWv2R9cWjapI39640rERbFRjFpS3rmEYyj9+mXOK61fY093LCOi4Ru2fOM1cqq2Wc4HU566ZcsVkr8sUnpFyN/AxPNeVQ4PsoLm/HW5+67LQ1y2ZwSRCIoSWoNsgZ3eV0Pb6MvcI9dDrUiWV3dsCor+S7ISGpbG2uIUwNWaiEPuuu+qvz9MyT3BOe07YD1UhUuKmCsCW7Jiqhf8RZ2e2FSD+e39jdswVN1UhV49+vbCrHfiQg6hWYKgYYNWacjHjrPi7OvYRT75yMf2au/N1K3ER3eKvnOv2rh9WHqE9u+Ytr0VWBKT/CyAlDX52mUdSDUjNqY6P6Sv10IfWxG0sb6ffDY93qh2ng9fgOrGKAdgXwPSxXccvRC/lAvqfm4mGd1C09JSbljkLf09TAinxjhzPPHJxMNCO9Bw=
