travis:
  secure:
    BINSTAR_TOKEN: ewTNnMcv0Iw3GABZ+Of+Hh/SA/4DyGU0Qb9JGH0Y5cNHiXrNMI5CEofmlOav1n2Lk7x96m7Gxyb4qoHDKKA5Z6FGL8GiOPN5glJegk9zWi3k2MmOBypMJhO6bThtZ0tV9ne2tiPkGRMBaHNYz/bq+xYYlC1F43U8iK0IArr7ODH02/TlAOi+n4hnrTWh1JTn73Djycc2TvO2KcQA9xWy53dsAmtCq0gQ+rWOjz2f/VlsubIVY8TXr9LQIhNAzX43CS6tw7CwH1+mbEue6svZU7975Irvr/8VHx4eo6q9shJjun2Tca86pwQdZ9M0YsCneJoCjEFJg1xCy88g1MUioGBY7rPQhgYanKR8NUUarf7RQg0HX0caJ0AlDBdmGRTY9/uCrlaTxDZsaLuhkBwyeksA25c5eFpeARSR55desYkveCtOYDdMnkxUmmyvPP1lSimDtC6LAzJ5CFqdj3ZF1enEt7VN3+8xkKisUBGbqA6yth+89tbVMeScOlPDGmtOwakaJCjHBxplVhmuWIDTXkPxMzFs5WSZPgwxCt4GPAUWfXoga+B+Hwot3Ia+nROxtQ+1vjVSi1rh+OXl0GEqfUGtlnhm3+5+0f+Fd/NBFcWQV35eFejvEPIyVOcg7SH494Ar5liD30G/xl8JpH50OomSz4RW3F09856Rg8jdJVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
